import type { Metadata } from "next";
import { jost, hanuman, inter } from "@/assets/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "The Cube",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${hanuman.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
